name: Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 构建
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/qqays/transmail-station:latest .

      # 推送
      - name: Push Docker image
        run: |
          docker push ghcr.io/qqays/transmail-station:latest
